server:
  port: 8080
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521/ORCLPDB1
    username: MNGARCIA
    password: 1
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  liquibase:
    change-log: classpath:/db/liquibase/master.db.changelog.xml

logging:
  file: target/mybatis-spring.log
  level:
    log4j.logger.com.ibatis: DEBUG
    log4j.logger.com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    log4j.logger.com.ibatis.common.jdbc.ScriptRunner: DEBUG
    log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
    log4j.logger.java.sql: DEBUG
    log4j.logger.java.sql.Connection: DEBUG
    log4j.logger.java.sql.Statement: DEBUG
    log4j.logger.java.sql.PreparedStatement: DEBUG
    log4j.logger.java.sql.ResultSet: DEBUG
    logger.com.ibatis: DEBUG
    logger.com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    logger.com.ibatis.common.jdbc.ScriptRunner: DEBUG
    logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
    logger.java.sql: DEBUG
    logger.java.sql.Connection: DEBUG
    logger.java.sql.Statement: DEBUG
    logger.java.sql.PreparedStatement: DEBUG
    logger.java.sql.ResultSet: DEBUG
    com.sample.mybatisspring.ibatis.mapper: TRACE

mybatis:
  type-aliases-package: com.sample.mybatisspring.domain
  type-handlers-package: com.sample.mybatisspring.ibatis.handlers
  mapper-locations:
  - classpath*:mybatis/**/*.xml

  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
    